---
- name: "Полное отключение автоматических обновлений"
  hosts: haproxy1
  become: true

  tasks:

    - name: Выключение /etc/apt/apt.conf.d/20auto-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";
        owner: root
        group: root
        mode: '0644'

    - name: Остановить службы автообновлений
      systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - unattended-upgrades
        - apt-daily.service
        - apt-daily.timer
        - apt-daily-upgrade.service
        - apt-daily-upgrade.timer

    - name: Отключить автозапуск служб автообновлений
      systemd:
        name: "{{ item }}"
        enabled: false
      loop:
        - unattended-upgrades
        - apt-daily.service
        - apt-daily.timer
        - apt-daily-upgrade.service
        - apt-daily-upgrade.timer

    - name: Маскировать службы автообновлений
      systemd:
        name: "{{ item }}"
        masked: true
      loop:
        - unattended-upgrades
        - apt-daily.service
        - apt-daily.timer
        - apt-daily-upgrade.service
        - apt-daily-upgrade.timer
